services:
  - type: web
    name: soundwave-duo
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        value: "*"
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://postgres:9141452138@Sasidhar@db.svjcreqwbtpmemhtkkej.supabase.co:5432/postgres
